name: loadmore_listview
description: Provide an easy-to-use Listview with load more items and refresh function
version: 1.0.7
homepage: https://github.com/stevenBang/loadmore_listview
repository: https://github.com/stevenBang/loadmore_listview

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.